#!/usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit

readonly BOX_NAME=$1
readonly USER_HOME="/home/$(whoami)"
readonly BOX_HOME="${USER_HOME}/.distrobox_homes/${BOX_NAME}"
readonly BOX_FONTS_PATH="${BOX_HOME}/.local/share/fonts"

mkdir -p "${BOX_HOME}"
ln -s "${USER_HOME}/.emacs.d" "${BOX_HOME}"
mkdir -p "${BOX_FONTS_PATH}"
ln -s ~/.local/share/fonts/* "${BOX_FONTS_PATH}"
